<?php
/** @var Zero1\ImprovedCheckoutSuccessPageHyva\Block\Onepage\Success $block */
?>
<div id="zero1-advanced-success" class="my-6">
    <div class="card">
        <h1 class="text-gray-900 page-title title-font font-bold text-3xl"><span><?php echo $block->getPageTitle(); ?></span></h1>
        <?php if ($block->getIntroText() != '') : ?>
            <p class="mt-4 mb-2"><?php echo $block->escapeHtml($block->getIntroText()); ?></p>
        <?php endif; ?>
        <?php echo $block->getChildHtml('checkout.registration.success'); ?>
    </div>

    <?php if ($block->getConfigFlag('order_information_row', 'enable') === true) : ?>
        <div class="flex flex-col lg:flex-row py-8 gap-4">
            <?php if ($block->getConfigFlag('order_information_row', 'enable_order_information') === true) : ?>
                <div class="card w-full order">
                    <h3 class="font-bold mb-2 text-2xl"><?php echo __('Order Details'); ?></h3>
                    <p><?php echo __('Order Number: '); ?><span><?php echo $block->escapeHtml($block->getOrderDetails()['incrementId']) ?></span></p>
                    <p><?php echo __('Order Total: '); ?><span><?php echo $block->escapeHtml($block->getOrderDetails()['baseGrandTotal']) ?></span></p>
                    <p><?php echo __('Order Date: '); ?><span><?php echo $block->escapeHtml($block->getOrderDetails()['createdAt']) ?></span></p>
                </div>
            <?php endif; ?>

            <?php if ($block->getConfigFlag('order_information_row', 'enable_shipping_information') === true) : ?>
                <?php $shippingDetails = $block->getShippingDetails(); ?>
                <?php if (!empty($shippingDetails)) : ?>
                    <div class="card w-full shipping">
                        <h3 class="font-bold mb-2 text-2xl"><?php echo __('Shipping Details'); ?></h3>
                        <?php if (!empty($shippingDetails['company'])) : ?>
                            <p><?php echo $block->escapeHtml($shippingDetails['company']); ?></p>
                        <?php endif; ?>
                        <?php if (!empty($shippingDetails['street'][0])) : ?>
                            <p><?php echo $block->escapeHtml($shippingDetails['street'][0]); ?></p>
                        <?php endif; ?>
                        <?php if (!empty($shippingDetails['street'][1])) : ?>
                            <p><?php echo $block->escapeHtml($shippingDetails['street'][1]); ?></p>
                        <?php endif; ?>

                        <?php if (!empty($shippingDetails['city'])) : ?>
                            <p><?php echo $block->escapeHtml($shippingDetails['city']); ?></p>
                        <?php endif; ?>

                        <?php if (!empty($shippingDetails['region'])) : ?>
                            <p><?php echo $block->escapeHtml($shippingDetails['region']); ?></p>
                        <?php endif; ?>

                        <?php if (!empty($shippingDetails['postcode'])) : ?>
                            <p><?php echo $block->escapeHtml($shippingDetails['postcode']); ?></p>
                        <?php endif; ?>

                        <?php if (!empty($shippingDetails['countryId'])) : ?>
                            <p><?php echo $block->escapeHtml($shippingDetails['countryId']); ?></p>
                        <?php endif; ?>

                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($block->getConfigFlag('order_information_row', 'enable_billing_information') === true) : ?>
                <?php $billingDetails = $block->getBillingDetails(); ?>
                <div class="card w-full billing">
                    <h3 class="font-bold mb-2 text-2xl"><?php echo __('Billing Details'); ?></h3>
                    <?php if (!empty($billingDetails['company'])) : ?>
                        <p><?php echo $block->escapeHtml($billingDetails['company']); ?></p>
                    <?php endif; ?>
                    <?php if (!empty($billingDetails['street'][0])) : ?>
                        <p><?php echo $block->escapeHtml($billingDetails['street'][0]); ?></p>
                    <?php endif; ?>
                    <?php if (!empty($billingDetails['street'][1])) : ?>
                        <p><?php echo $block->escapeHtml($billingDetails['street'][0]) . ' ' . $block->escapeHtml($billingDetails['street'][1]); ?></p>
                    <?php endif; ?>
                    <?php if (!empty($billingDetails['city'])) : ?>
                        <p><?php echo $block->escapeHtml($billingDetails['city']); ?></p>
                    <?php endif; ?>
                    <?php if (!empty($billingDetails['region'])) : ?>
                        <p><?php echo $block->escapeHtml($billingDetails['region']); ?></p>
                    <?php endif; ?>
                    <?php if (!empty($billingDetails['postcode'])) : ?>
                        <p><?php echo $block->escapeHtml($billingDetails['postcode']); ?></p>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php if ($block->getStaticBlockToRender() !== null) : ?>
        <div class="mb-8">
            <?php echo $block->getStaticBlockToRender(); ?>
        </div>
    <?php endif; ?>

    <?php 
    /* TODO - Error in class getting related products - need revising
    <?php if ($block->relatedProductsAreAbleToRender() === true) : ?>
        <?php if (!empty($block->getRelatedProducts())) : ?>
            <div class="card">
                <?php if ($block->getRelatedProductsTitleText() !== null) : ?>
                    <h3 class="font-bold mb-2 text-2xl"><?php echo $block->escapeHtml($block->getRelatedProductsTitleText()); ?></h3>
                <?php endif; ?>
                <div class="grid grid-cols-2 lg:flex lg:flex-row">
                    <?php $count = 0; ?>
                    <?php foreach ($block->getRelatedProducts() as $relatedProduct) : ?>
                        <?php $count++ ;?>
                        <div class="w-full p-2">
                            <a href="<?php echo $block->escapeUrl($relatedProduct->getProductUrl()); ?>">
                                <img class="w-full m-0" src="<?php echo $block->escapeHtml($block->getRelatedProductImage($relatedProduct)); ?>"
                                     alt="<?php echo $block->escapeHtml($relatedProduct->getName()); ?>" />
                            </a>
                            <a href="<?php echo $block->escapeUrl($relatedProduct->getProductUrl()); ?>">
                                <h5><?php echo $block->escapeHtml($relatedProduct->getName()); ?></h5>
                            </a>
                            <p><?php echo $block->escapeHtml($block->getCurrentCurrencyCode() .
                                    number_format($relatedProduct->getPrice(), 2)); ?>
                            </p>
                        </div>
                        <?php if ($count >= $block->getMaximumNumberOfRelatedProductsToDisplay()) {
                            break;
                        } ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    */ ?>
    
    <?php if ($block->getNewsletterBlock() !== null) : ?>
        <div class="card">
            <?php echo $block->getNewsletterBlock(); ?>
        </div>
    <?php endif; ?>
    
</div>
